"""
Jinja2-based framework export generator for GitScape.ai.

Renders Python boilerplate that wraps the generated skill package
for use with specific agentic frameworks (Google ADK, Agno).

Author: João Machete
"""

from jinja2 import Environment, BaseLoader

# ─── Templates ────────────────────────────────────────────────────────────────

ADK_TEMPLATE = '''\
"""
{{ display_name }} — Google ADK Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from google.adk.agents import Agent
    from {{ module_name }}_adk_skill import {{ class_name }}Skill

    root_agent = Agent(
        name="{{ skill_name }}-agent",
        model="gemini-2.0-flash",
        instruction="...",
        tools=[{{ class_name }}Skill()],
    )
"""
from google.adk.tools import FunctionTool
from pathlib import Path

# Path to the SKILL.md and DIGEST.md knowledge base bundled with this skill
_SKILL_DIR = Path(__file__).parent
_SKILL_MD = (_SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
_DIGEST_MD = (_SKILL_DIR / "DIGEST.md").read_text(encoding="utf-8")


def query_{{ module_name }}_codebase(question: str) -> str:
    """
    Query the {{ display_name }} codebase knowledge base.

    Use this tool when the user asks about the {{ display_name }} repository:
    architecture, implementation, APIs, configuration, bugs, or how to extend it.

    Args:
        question: The specific question about the {{ display_name }} codebase.

    Returns:
        A detailed answer grounded in the repository source code.
    """
    # In production, replace this stub with your preferred LLM call.
    # The full digest is in _DIGEST_MD — pass it as system context.
    return (
        f"[{{ display_name }} Skill] Question received: {question}\\n"
        f"Load DIGEST.md as system context and answer using: {_DIGEST_MD[:500]}..."
    )


{{ class_name }}Skill = FunctionTool(func=query_{{ module_name }}_codebase)

__all__ = ["{{ class_name }}Skill"]
'''

AGNO_TEMPLATE = '''\
"""
{{ display_name }} — Agno Knowledge Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from agno.agent import Agent
    from {{ module_name }}_agno_skill import {{ class_name }}Knowledge

    agent = Agent(
        name="{{ skill_name }}-agent",
        knowledge={{ class_name }}Knowledge,
        search_knowledge=True,
    )
    agent.knowledge.load()
"""
from pathlib import Path
from agno.knowledge.text import TextKnowledgeBase
from agno.vectordb.lancedb import LanceDb, SearchType

# Path to the DIGEST.md knowledge base bundled with this skill
_SKILL_DIR = Path(__file__).parent
_DIGEST_PATH = _SKILL_DIR / "DIGEST.md"

{{ class_name }}Knowledge = TextKnowledgeBase(
    path=str(_DIGEST_PATH),
    vector_db=LanceDb(
        table_name="{{ module_name }}_skill",
        uri=str(_SKILL_DIR / ".lancedb"),
        search_type=SearchType.hybrid,
    ),
)

__all__ = ["{{ class_name }}Knowledge"]
'''

# ─── Renderer ─────────────────────────────────────────────────────────────────

_jinja_env = Environment(loader=BaseLoader(), autoescape=False)


def _to_class_name(owner: str, repo: str) -> str:
    """Convert 'my-repo' → 'MyRepo' style PascalCase."""
    combined = f"{owner}_{repo}"
    return "".join(
        word.capitalize() for word in combined.replace("-", "_").split("_")
    )


def _to_module_name(owner: str, repo: str) -> str:
    """Convert to snake_case module name."""
    combined = f"{owner}_{repo}".lower()
    return combined.replace("-", "_")


def _to_skill_name(owner: str, repo: str) -> str:
    return f"{owner.lower()}-{repo.lower()}"


def render_framework_export(
    framework: str,
    owner: str,
    repo: str,
) -> str:
    """
    Render a Python framework export file for the given framework.

    Args:
        framework: 'adk' or 'agno'
        owner: GitHub repository owner
        repo: GitHub repository name

    Returns:
        Rendered Python source code string.

    Raises:
        ValueError: If framework is not supported.
    """
    framework = framework.lower()
    templates = {"adk": ADK_TEMPLATE, "agno": AGNO_TEMPLATE}

    if framework not in templates:
        raise ValueError(
            f"Unsupported framework '{framework}'. Supported: {list(templates.keys())}"
        )

    context = {
        "display_name": f"{owner}/{repo}",
        "class_name": _to_class_name(owner, repo),
        "module_name": _to_module_name(owner, repo),
        "skill_name": _to_skill_name(owner, repo),
    }

    tmpl = _jinja_env.from_string(templates[framework])
    return tmpl.render(**context)
